// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpwa0QxMphoFhduX34QENVZ3gxuYgAV5E',
    appId: '1:183501227160:web:34fe7c670f278877727ced',
    messagingSenderId: '183501227160',
    projectId: 'food-delivery-app-97408',
    authDomain: 'food-delivery-app-97408.firebaseapp.com',
    storageBucket: 'food-delivery-app-97408.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp7EnQgtZXJsGfmepgqvTPN18va_N8Wyc',
    appId: '1:183501227160:android:f656f767a41d96c9727ced',
    messagingSenderId: '183501227160',
    projectId: 'food-delivery-app-97408',
    storageBucket: 'food-delivery-app-97408.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOx3ZEcGRSpnmhK-hBv1eH1SxzIyyFKUo',
    appId: '1:183501227160:ios:7a9ab49f5c42a2b5727ced',
    messagingSenderId: '183501227160',
    projectId: 'food-delivery-app-97408',
    storageBucket: 'food-delivery-app-97408.appspot.com',
    androidClientId: '183501227160-it902d56t4snj006gm2ov39t95v48k7o.apps.googleusercontent.com',
    iosClientId: '183501227160-64prjoaa0s9ibhvgcm7qfe9cfnadbmd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryWithProviderUsingFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOx3ZEcGRSpnmhK-hBv1eH1SxzIyyFKUo',
    appId: '1:183501227160:ios:7a9ab49f5c42a2b5727ced',
    messagingSenderId: '183501227160',
    projectId: 'food-delivery-app-97408',
    storageBucket: 'food-delivery-app-97408.appspot.com',
    androidClientId: '183501227160-it902d56t4snj006gm2ov39t95v48k7o.apps.googleusercontent.com',
    iosClientId: '183501227160-64prjoaa0s9ibhvgcm7qfe9cfnadbmd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryWithProviderUsingFirebaseApp',
  );
}
